name: vuln_scan_action

on:
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use File from Repository
        run: |
          unzip afrog.zip
          unzip mp.zip -d /home/runner/afrog-pocs

      - name: Execute based on type
        run: |
          chmod 777 afrog
          ./afrog -duc -doh -s CVE-2024-4956 -T url.txt -ja rs.json
      - name: Validate rs.json
        run: |
          sync  # 强制同步所有挂起的写入操作
          ls -lh rs.json
          jq . rs.json
          cat rs.json
          
      - name: Upload rs.json as artifact
        uses: actions/upload-artifact@v2
        with:
          name: rs-json
          path: rs.json
