name: vuln_scan_action

on:
  repository_dispatch:
    types:
      - afrog

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use File from Repository
        run: |
          unzip afrog.zip
          unzip mp.zip -d /home/runner/afrog-pocs
          
      - name: get targets
        run: curl -o url.txt ${{ github.event.client_payload.downloadurl }}
        
      - name: Execute based on type
        run: |
          chmod 777 afrog
          ./afrog -duc -doh -s ${{ github.event.client_payload.template_id }} -T url.txt -ja rs.json
      - name: Validate rs.json
        run: |
          sync  # 强制同步所有挂起的写入操作
          file_path="path/to/your/file"
          if [ -f "$file_path" ]; then
            echo "File exists"
          else
            exit 0
          fi
          ls -lh rs.json
          jq . rs.json
          
      - name: Send JSON to Server
        run: |
          curl -X POST ${{ github.event.client_payload.webhook_url }} \
          -H "Content-Type: application/json" \
          --data-binary @rs.json
