name: vuln_scan_action

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use File from Repository
        run: |
          unzip afrog.zip
          unzip mp.zip -d mypoc

      - name: Execute based on type
        run: |
          chmod 777 afrog
          ./afrog -duc -P mypoc -s CVE-2024-4956 -T url.txt -ja rs.json
          cat rs.json
